### ISSUE TITLE
Export all applications

### ISSUE THREAD

**Issue by jennifermarie** [codeforamerica/intake#964] opened 2017-06-15 22:36 UTC
- [ ]  CSV spreadsheet mockup
- [ ]  Excel 2007 has a row, cell, column limit (so just check those)
- [ ]  Create view that returns a spreadsheet directly
```
import csv

def get_fields_for_org(org):
    # selects context keys from form linked to org 
    # fetches values for those keys from formsubmission
    # get display form
    # iterate over fields & get_display_value
    # exclude declaration letter for now

def get_status_updates_for_app(app):
    # attaches (flat) set of status updates to row 

def csv_for_apps(applications_queryset):
    csv_writer

class AppsCSVView(View):
    # login required

# implement as button "Export all application data as csv" on All Applications Index 

CSVExportSerializer(serializers.Serializer):
# fields

```
UAT
- import into old Excel and ensure it turns out correctly
Testing:
- permission tests
- test that the values are reasonable and nice
Browser test
- navigate to it and click the button and get a file

1.5 days

**Comment by TiffanyAndrews** [comment] 2017-08-08 23:11
county partner DB: https://docs.google.com/presentation/d/1CfS1cGev6n5vFVoKe56iwD8xEjKWK7KAJre9cZf8JfY/edit#slide=id.g249e8265f1_0_40

**Comment by rossettistone** [comment] 2017-09-13 20:58
This looks like a duplicate of #72. @bengolder, can you confirm?

**Comment by bengolder** [comment] 2017-09-13 20:59
@rossettistone yes it is! and adds useful context

**Closed as completed** 2017-09-22 23:52 UTC
Labels: county request, in progress
